[project]
name = "lab3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apache-airflow==3.1.7",
    "kneed>=0.8.5",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
]
